package:
  name: pcntoolkit
  version: "0.30.0"

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - pymc # includes numpy, scipy, pandas, arviz
    - six
    - scikit-learn
    - matplotlib
    - pytorch
    - cpuonly
    - sphinx-tabs
    - nibabel
  pip:
    - bspline

# test:
#   imports:
#     - your_project_name

about:
  home: http://github.com/amarquand/PCNtoolkit
  license: 'GNU GPLv3'
  summary: 'Predictive Clinical Neuroscience toolkit'
  description: |
    'Predictive Clinical Neuroscience toolkit'
  doc_url: https://pcntoolkit.readthedocs.io/en/latest/
  dev_url: http://github.com/amarquand/PCNtoolkit

extra:
  recipe-maintainers:
    - AuguB